# Generated by Django 3.2.16 on 2022-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designationi',
            new_name='designation',
        ),
    ]
